// AUTO-GENERATED by scripts/generate-carousel-manifest.mjs — do not edit.
// Drop clips into public/assets/carousel/ and run `npm run carousel:manifest`
// (or any build) to regenerate.

export interface CarouselSlide {
    id: string;
    /** Optimized 720p .mp4 when available; otherwise the original master. */
    video: string;
    /** First-frame JPG for instant visual fill while video data loads.
     *  Null when the optimizer hasn't run for this clip yet. */
    poster: string | null;
    alt: string;
}

export const CAROUSEL_SLIDES: readonly CarouselSlide[] = [
    {
        "id": "01",
        "video": "/assets/carousel/web/01.mp4",
        "poster": "/assets/carousel/posters/01.webp",
        "alt": "01"
    },
    {
        "id": "02",
        "video": "/assets/carousel/web/02.mp4",
        "poster": "/assets/carousel/posters/02.webp",
        "alt": "02"
    },
    {
        "id": "03",
        "video": "/assets/carousel/web/03.mp4",
        "poster": "/assets/carousel/posters/03.webp",
        "alt": "03"
    },
    {
        "id": "04",
        "video": "/assets/carousel/web/04.mp4",
        "poster": "/assets/carousel/posters/04.webp",
        "alt": "04"
    },
    {
        "id": "05",
        "video": "/assets/carousel/web/05.mp4",
        "poster": "/assets/carousel/posters/05.webp",
        "alt": "05"
    },
    {
        "id": "06",
        "video": "/assets/carousel/web/06.mp4",
        "poster": "/assets/carousel/posters/06.webp",
        "alt": "06"
    },
    {
        "id": "07",
        "video": "/assets/carousel/web/07.mp4",
        "poster": "/assets/carousel/posters/07.webp",
        "alt": "07"
    },
    {
        "id": "08",
        "video": "/assets/carousel/web/08.mp4",
        "poster": "/assets/carousel/posters/08.webp",
        "alt": "08"
    },
    {
        "id": "09",
        "video": "/assets/carousel/web/09.mp4",
        "poster": "/assets/carousel/posters/09.webp",
        "alt": "09"
    },
    {
        "id": "10",
        "video": "/assets/carousel/web/10.mp4",
        "poster": "/assets/carousel/posters/10.webp",
        "alt": "10"
    },
    {
        "id": "11",
        "video": "/assets/carousel/web/11.mp4",
        "poster": "/assets/carousel/posters/11.webp",
        "alt": "11"
    }
];
